name: Release Rules

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy
      env:
        MAPPING_FILE: mapping.json
        API_ENDPOINT: "https://api.rixcloud.io/v2"
        USER_TOKEN: ${{ secrets.USER_TOKEN }}

      run: |
        curl -sSL https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o jq
        chmod +x jq
        export JQ="./jq"
        RULESETS=$(cat $MAPPING_FILE | $JQ -r "keys | join(\" \")")
        
        for RULE in $RULESETS; do
          RULE_NAME=$(cat $MAPPING_FILE | $JQ -r '.["'$RULE'"]')

          # POST as rule set
          echo "Starting upload $RULE_NAME"

          $JQ -n --rawfile data $RULE_NAME '{"data": $data}' | curl -X PATCH \
              $API_ENDPOINT/profile/cloud/ruleset/$RULE \
              -H "Content-Type: application/json; charset=utf-8" \
              -u $USER_TOKEN \
              -d @- \
              -s 

          echo ""
        done
